[package]
name = "Rust-template"
version = "0.1.0"
authors = ["anthony"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustfix = "0.5.1"
libc = "0.2.82"
[[bin]]
name = "Rust-template"
path = "main.rs"
